{% set name = "openinference-instrumentation-vertexai" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openinference_instrumentation_vertexai-{{ version }}.tar.gz
  sha256: ba337c0648477b526aaede7506678561a0b2e2461a91e4758648b153c394d079

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.13
    - hatchling
    - pip
  run:
    - python >=3.8,<3.13
    - opentelemetry-api
    - opentelemetry-instrumentation
    - opentelemetry-semantic-conventions
    - openinference-instrumentation >=0.1.7
    - openinference-semantic-conventions
    - wrapt

test:
  imports:
    - openinference.instrumentation.vertexai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Arize-ai/openinference
  summary: OpenInference VertexAI Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RogerHYang
